Added the enable_private_endpoint in main.tf
Added the enable_private_endpoint = true in terraform/main.tf to resolve the following issue:
Error: Missing required argument

  on main.tf line 130, in resource "google_container_cluster" "primary":
 130:   private_cluster_config {

The argument "enable_private_endpoint" is required, but no definition was
found.